### ISSUE TITLE
Customizing AniMet

### ISSUE THREAD

**Issue by yraheja77** [ECCC-MSC/msc-animet#18]
Hi, I would like to customize AniMet to include my own data layers. eg If I want to see the Postal Code-wise population affected by current weather conditions. Do we have that functionality built-in right now?

**Comment by alexandreleroux** [comment]
Thanks for your interest in AniMet. We are considering adding the capability for users to use custom WMS Server sources and overlay content from these servers. We haven't implemented this feature yet though. 

Given AniMet's code is open, you can implement this feature sooner if you really need it in the short term. Hope this helps!

**Comment by PhilippeTh** [comment]
@yraheja77 AniMet currently only supports WMS sources. There is a functionality (that will also receive an improvement within the next few weeks) to allow people who fork AniMet to add their own WMS sources if that's what you were looking for. However, AniMet has been built to read getCapabilities xml formatted a certain way and so not any source can just easily be added. If that is indeed what you're doing, would you be able to send an example URL for your getCapabilities so that I may tell you right away if it would be possible?

Thank you.

**Comment by PhilippeTh** [comment]
Officially added how to add custom WMS sources in the README https://github.com/ECCC-MSC/msc-animet#adding-custom-wms-sources.

With that I'll be closing this issue.
